DATA_DIR = "../data/captcha_images_v2"
CHECKPOINT_PATH = "../checkpoint"
PLOT_PATH = "../plots"
# DATA_DIR = "/content/drive/MyDrive/data/captcha"
# CHECKPOINT_PATH = "/content/drive/MyDrive/data/checkpoint"
# PLOT_PATH = "/content/drive/MyDrive/data/plots"
BATCH_SIZE = 8
IMAGE_WIDTH = 300
IMAGE_HEIGHT = 75
NUM_WORKERS = 0
DEVICE = "cpu"
EPOCHS = 2